id: P008010
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:55:09.479584
source_metadata:
  id: bdr:W2PD17614
  title: '口述当代西藏第一

    '
  author: ''
  volumes:
    a4f8b7a6d360479cb112ce6ee7d1bdc1:
      image_group_id: I4PD4237
      title: Volume 1 of 口述当代西藏第一
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
