id: P008010
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17614
  title: '口述当代西藏第一

    '
  author: ''
  volumes:
    ecc98a48ad454ef6bb2e1e626a521bb4:
      image_group_id: I4PD4237
      title: ''
      volume_number: 1
      total_pages: 266
ebook_metadata:
  title: '口述当代西藏第一

    '
  author: ''
  sku: P008010
  cover: cover.jpg
  layers:
  - pagination
